version: '2'
services:
    elancer-app:
        image: elancer
        external_links:
            - elancer-mysql:mysql
            - elancer-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/elancer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    elancer-mysql:
        extends:
            file: mysql.yml
            service: elancer-mysql
    elancer-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: elancer-elasticsearch
